url: https://maddie-eckhart.github.io
baseurl: /Learning-Jekyll/

# Site settings
title: Madeline Eckhart
email: madelineaeckhart@gmail.com
description: "Maddie's professional website to show projects, experience, and passion."


# Team names, titles and social links
people:
- name: Madeline Eckhart
  pic: 1
  position: 
  social:
    - title: github
      url: http://github.com/maddie-eckhart 
    - title: linkedin
      url: https://www.linkedin.com/in/madeline-eckhart/
    - title: medium
      url: https://medium.com/@madelineaeckhart

# Build settings
markdown: kramdown
permalink: pretty