url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Madeline Eckhart
email: madelineaeckhart@gmail.com
description: "Maddie's proffessional website to show projects, experience, and passion."


# Team names, titles and social links
people:
- name: Madeline Eckhart
  pic: 1
  position: Lead Designer
  social:
    - title: github
      url: http://github.com/maddie-eckhart 
    - title: linkedin
      url: https://www.linkedin.com/in/madeline-eckhart/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/madeline-eckhart/
  - title: github
    url: http://github.com/maddie-eckhart 

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty